import Logo from "../components/Logo";
import Footer from "../components/Footer";

export default function TermsOfService() {
  return (
    <>
      <Logo />
      <h1 className="text-4xl font-semibold my-auto mx-20 mb-4">
        Noteless Terms of Service
      </h1>
      <div className="flex  flex-col gap-4 mx-20 mb-10">
        <p>
          Terms of Service for Noteless
          <br />
          Effective Date: 29/10/2024
        </p>
        <h2 className="text-2xl font-semibold">1. Acceptance of Terms</h2>
        <p>
          By accessing or using Noteless, operated by Metaverse Lab Limited, you
          agree to comply with and be bound by these Terms of Service.
        </p>
        <h2 className="text-2xl font-semibold">2. Use of the Service</h2>
        <p>
          You must be at least 18 years old to use Noteless. You agree to use
          Noteless only for lawful purposes.
        </p>
        <h2 className="text-2xl font-semibold">3. User Accounts</h2>
        <p>
          You must provide accurate and complete information when creating an
          account. You are responsible for maintaining the confidentiality of
          your account credentials.
        </p>
        <h2 className="text-2xl font-semibold">
          4. Content and Intellectual Property
        </h2>
        <p>
          Users have full rights to use the content generated by Noteless as
          they see fit. Users retain rights to their original content uploaded
          to Noteless.
        </p>
        <h2 className="text-2xl font-semibold">
          5. Communication and Marketing
        </h2>
        <p>
          By registering, you consent to receive emails from us, including
          newsletters and promotional materials. You can unsubscribe at any
          time.
        </p>
        <h2 className="text-2xl font-semibold">6. Payment and Billing</h2>
        <p>
          Payments for services are processed via Stripe. All fees are
          non-refundable unless otherwise specified.
        </p>
        <h2 className="text-2xl font-semibold">7. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your account if you
          violate these Terms of Service.
        </p>
        <h2 className="text-2xl font-semibold">8. Limitation of Liability</h2>
        <p>
          Noteless is provided "as is." We do not guarantee its availability or
          functionality. Metaverse Lab Limited is not liable for any direct,
          indirect, incidental, or consequential damages resulting from your use
          of the service.
        </p>
        <h2 className="text-2xl font-semibold">9. Changes to Terms</h2>
        <p>
          We may update these Terms of Service. You will be notified of
          significant changes via email or through our website.
        </p>
        <h2 className="text-2xl font-semibold">10. Governing Law</h2>
        <p>These terms are governed by the laws of Hong Kong.</p>
        <h2 className="text-2xl font-semibold">11. Contact Information</h2>
        <p>
          If you have any questions, please contact us at charles@voxelai.ai.
        </p>
      </div>
      <Footer />
    </>
  );
}
